### ISSUE TITLE
[Version 2.0] Alternatives to running measurement in background

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/ooniprobe-ios#48]
In the second release of the app I want to add the possibility to run background measurements, possibly without the intervention of the user.
I will keep open this issue to write down ideas and discussion.

At the moment one option is to send a local notification to the user at a specific time of the day, when the user taps on the notification it opens the app and start the measurements.

**Comment by bassosimone** [comment]
What is it possible to do when you receive a notification? Can you also run some code to process it or are you limited to showing the notification to the user?

**Comment by lorenzoPrimi** [comment]
Showing it to the user, if the user taps on that any code can be executed and the app will go from background to foreground.

**Comment by bassosimone** [comment]
Thanks! Uhm, so the plan would be to send a notification whenever a new measurement is to be run, I assume, because sending a notification for every URL would be very annoying.

At the same time, also a notification for a new measurement poses the problem that one must keep the app open for a long time. *What a pain*. I think we should find a way to run in background, perhaps using for example the VPN interface for this purpose. Do you think this makes sense?

**Comment by lorenzoPrimi** [comment]
At the moment this topic is not about keeping the measurement in the background because they take a long time, but achieve the running of the daily measurement. As there is no cronjob I thought about local notification like an alarm.

For what you are saying I'm investigating into Apple's background mode, but there is a chance the app gets killed if the system is running out of resources and there is nothing we can do to prevent them.
Btw, for me it's not a pain, look at the PokemonGo solution, it's the optimal solution, they just turn off the display and the app keeps running in foreground.

**Comment by bassosimone** [comment]
> At the moment this topic is not about keeping the measurement in the background because they take a long time, but achieve the running of the daily measurement. As there is no cronjob I thought about local notification like an alarm.

Right. Well, I guess using push notifications makes a lot of sense to implement that.

> For what you are saying I'm investigating into Apple's background mode, but there is a chance the app gets killed if the system is running out of resources and there is nothing we can do to prevent them.

Okay, thanks, let us know how this research progress! Regarding the likelihood that an application is killed by the system, do you know how could I check whether this happens on my iPhone? That is, the applications I see when I double click on the home button, can I assume they are still running?

> Btw, for me it's not a pain, look at the PokemonGo solution, it's the optimal solution, they just turn off the display and the app keeps running in foreground.

I've never played with PokemonGo, even though I have seen people using it around me. Is the screen saver enabled in that case? I mean, the ideal scenario is that you keep the app in your pocket rather than bringing it around while tests are running. (After all there is a bigger incentive in running PokemonGo than to run ooniprobe-ios, given that the former gamifies you.)

**Comment by lorenzoPrimi** [comment]
No, the app you see when you double click on the home button could already have been deallocated. From an user point of view you see it when you reopen the app and you see the launch image again; or the activity you were running is not the same (ex. you were navigating a map and when you open maps again you see your current position)
From a developer point of view this method will be called
```
- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

```

What PokemonGo does is creating a black screen saver (when you turn the device upside down) and setting the brightness to minimum to save battery, to prevent any unintentional touch on the screen when you put the phone in the screen and keep walking.
I guess we just found an optimal way to achieve this without having to investigate much on the background mode (that have to be approved by apple btw, and not always they do)

**Comment by bassosimone** [comment]
Thank you for the detailed reply!

> I guess we just found an optimal way to achieve this without having to investigate much on the background mode

To be honest, I am not sure that this mode is optimal. I probably have to think a little more about this, but from my current point of view running in background has more advantages. In any case, given that this is not something to be implemented soon, I'd say we can table this discussion for now and perhaps we can discuss this in the future when the notification part has been implemented.

**Comment by lorenzoPrimi** [comment]
I already started enabling background modes on iOS and the local push notification to Schedule tests and show when test is complete and app not running.

"Now comes the essential bit: the call to beginBackgroundTaskWithExpirationHandler:. This is the method that tells iOS that you need more time to complete whatever it is you’re doing in case the app is backgrounded. After this call, if your app is backgrounded it will still get CPU time until you call endBackgroundTask:."

Some links about background tasks in iOS:
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html
https://developer.apple.com/reference/uikit/uiapplication/1623051-beginbackgroundtaskwithname
https://www.raywenderlich.com/143128/background-modes-tutorial-getting-started
https://www.raywenderlich.com/29948/backgrounding-for-ios

**Comment by lorenzoPrimi** [comment]
I guess we can close this. Background is working now.
