### ISSUE TITLE
Possibly not using correct network interface?

### ISSUE THREAD

**Issue by willscott** [measurement-kit/ooniprobe-ios#61]
Running on cell data, both the invalid request line and ndt test seem to run off of probe IP of 127.0.0.1, and can't contact anything remote.

**Comment by willscott** [comment]
![signal-2017-01-23-175120](https://cloud.githubusercontent.com/assets/428199/22215972/14ce4bce-e152-11e6-8534-28cb50d07671.jpeg)

**Comment by willscott** [comment]
And the verbose log:
```
http::request: {
http::request:     dns/engine => system
http::request:     geoip_asn_path => /var/containers/Bundle/Application/snip/measurement-kit-test.app/GeoIPASNum.dat
http::request:     geoip_country_path => /var/containers/Bundle/Application/snip/measurement-kit-test.app/GeoIP.dat
http::request:     http/method => GET
http::request:     http/url => http://geoip.ubuntu.com/lookup
http::request:     no_file_report => 1
http::request:     save_real_probe_ip => 1
http::request: }
resolve_hostname: geoip.ubuntu.com
resolve_hostname: ipv4...
resolve_hostname: ipv4... done
resolve_hostname: ipv6...
resolve_hostname: ipv6... done
connect_first_of begin
connect_base 91.189.94.25:80
connect_first_of failure
connect_first_of begin
connect_base 91.189.89.144:80
connect_first_of failure
connect_first_of begin
connect_base 2607:7700:0:19::5bbd:5e19:80
connect_first_of failure
connect_first_of begin
connect_base 2607:7700:0:19::5bbd:5990:80
connect_first_of failure
connect_first_of begin
connect_first_of all addresses failed
ip_lookup() failed: error code: 1003
ip address of resolver is 208.54.144.225
Results collector: https://b.collector.test.ooni.io:4441
Opening report; please be patient...
resolve_hostname: b.collector.test.ooni.io
resolve_hostname: ipv4...
resolve_hostname: ipv4... done
resolve_hostname: ipv6...
resolve_hostname: ipv6... done
connect_first_of begin
connect_base 37.218.240.140:4441
connect_first_of failure
connect_first_of begin
connect_base 2607:7700:0:19::25da:f08c:4441
connect_first_of failure
connect_first_of begin
connect_first_of all addresses failed
Opening report... 1003
net_test: running next measurement
net_test: creating entry
net_test: calling setup
net_test: running with input 
query mlabns for tool ndt
mlabns url: https://mlab-ns.appspot.com/ndt
http::on request: {
http::request:     dns/engine => system
http::request:     geoip_asn_path => /var/containers/Bundle/Application/snip/measurement-kit-test.app/GeoIPASNum.dat
http::request:     geoip_country_path => /var/containers/Bundle/Application/snip/measurement-kit-test.app/GeoIP.dat
http::request:     http/method => GET
http::request:     http/url => https://mlab-ns.appspot.com/ndt
http::request:     no_file_report => 1
http::request:     save_real_probe_ip => 1
http::request:     test_suite => 4
http::request: }
resolve_hostname: mlab-ns.appspot.com
resolve_hostname: ipv4...
net_test: running next measurement
net_test: reached end of input
net_test: running next measurement
net_test: reached end of input
resolve_hostname: ipv4... done
resolve_hostname: ipv6...
resolve_hostname: ipv6... done
connect_first_of begin
connect_base 216.58.193.113:443
connect_first_of failure
connect_first_of begin
connect_base 2607:f8b0:400a:809::2011:443
connect_first_of failure
connect_first_of begin
connect_first_of all addresses failed
Test failed: {unknown_failure 8024} [{connect_error}]
query mlabns for tool neubot
mlabns url: https://mlab-ns.appspot.com/neubot
http::request: {
http::request:     dns/engine => system
http::request:     geoip_asn_path => /var/containers/Bundle/Application/snip/measurement-kit-test.app/GeoIPASNum.dat
http::request:     geoip_country_path => /var/containers/Bundle/Application/snip/measurement-kit-test.app/GeoIP.dat
http::request:     http/method => GET
http::request:     http/url => https://mlab-ns.appspot.com/neubot
http::request:     mlabns_tool_name => neubot
http::request:     no_file_report => 1
http::request:     save_real_probe_ip => 1
http::request:     test_suite => 128
http::request: }
resolve_hostname: mlab-ns.appspot.com
resolve_hostname: ipv4...
resolve_hostname: ipv4... done
resolve_hostname: ipv6...
resolve_hostname: ipv6... done
connect_first_of begin
connect_base 216.58.193.113:443
connect_first_of failure
connect_first_of begin
connect_base 2607:f8b0:400a:809::2011:443
connect_first_of failure
connect_first_of begin
connect_first_of all addresses failed
Test failed: {unknown_failure 8024} [{connect_error}]
Cannot access Web100 data
Cannot access connect times
Did not find any reliable way to compute RTT
Cannot compute download speed
Cannot access Web100 data
Cannot access connect times
Did not find any reliable way to compute RTT
Cannot compute download speed
Single- and multi-stream ping are null
net_test: tearing down
cannot write entry
net_test: running next measurement
net_test: reached end of input
ooni_reporter: missing report ID
```

**Comment by bassosimone** [comment]
So:

```
connect_first_of begin
connect_base 91.189.94.25:80
connect_first_of failure
connect_first_of begin
connect_base 91.189.89.144:80
connect_first_of failure
connect_first_of begin
connect_base 2607:7700:0:19::5bbd:5e19:80
connect_first_of failure
connect_first_of begin
connect_base 2607:7700:0:19::5bbd:5990:80
connect_first_of failure
connect_first_of begin
connect_first_of all addresses failed
```

to completely understand what happens we need to expose low level errors. This bit of work (long overdue) has now been submitted as measurement-kit/measurement-kit#1098.

I am really curious to know which is the low-level error because of which connect to IPv4 fails here. As regards IPv6, it seems to me that [we're incorrectly assembling the endpoint](https://github.com/measurement-kit/measurement-kit/blob/1b566891710c8c9f99c25c037d5eabd952067ef8/src/libmeasurement_kit/net/connect_impl.hpp#L36) and we should instead [use the proper functionality to quote the IPv6 endpoint](https://github.com/measurement-kit/measurement-kit/blob/dcf22476f19de111d0a855946e08ba68cf68f070/src/libmeasurement_kit/net/utils.cpp#L76) or bypass libevent parsing and do our own expansion of endpoints that also takes into account the scope, which IIRC is not managed by libevent. Anyways, this bug is clearly related to #955.

**Comment by bassosimone** [comment]
So, for the records, with measurement-kit/measurement-kit#1100 and measurement-kit/measurement-kit#1101 applied, measurement-kit/ios-example@747603dac99d65b477471c2a07e56ff898909eb6 works for @willscott in the above scenario. Relevant excerpt from the logs:

```
Results collector: https://b.collector.test.ooni.io:4441
Opening report; please be patient...
resolve_hostname: b.collector.test.ooni.io
resolve_hostname: ipv4...
resolve_hostname: ipv4... done
resolve_hostname: ipv6...
resolve_hostname: ipv6... done
connect_first_of begin
connect_base 37.218.240.140:4441
connect() failed immediately
reason why connect() has failed: network_unreachable
connect_first_of failure
connect_first_of begin
connect_base 2607:7700:0:19::25da:f08c:4441
connect() in progress...
connect time: 1.290950
connect_first_of success
ca_bundle_path: 
connect ssl...
connect ssl... callback
```

I guess that, when ooniprobe-ios is recompiled to include the current `stable` branch, the problem will likely go away also for it. (Currently the library prefers IPv4 to IPv6, but since connect fails immediately, I don't think it is necessary to speed up connect() to add custom logic to reorder the preferences to favour IPv6 when it's clear that there is no IPv4 connectivity.)

**Comment by willscott** [comment]
Upon upgrade, this gets further - in that the test starts running, but the test itself seems to still have problems on my device.  This is on version 19; perhaps it doesn't have the current `stable` MK library yet?

![signal-2017-01-25-174705](https://cloud.githubusercontent.com/assets/428199/22302374/6461ad2e-e2e3-11e6-92c5-9c37592b56b0.jpeg)

**Comment by bassosimone** [comment]
Ah, damn! So, I think I can improve things on the measurement-kit side (and generally I believe this could be helpful, what do you think @hellais) by adding:

```
    engine_name: measurement-kit
    engine_version: v0.4.0-beta.1-38-gea78f1de
```

The latter can be obtained with `git describe --tags` when the sources are configured (tor does something similar). I think this would be very useful to know what code is running.

However, this will only answer the question "what version of measurement-kit am I exactly using?", which is useful but only part of the story. To know more, I need to see logs. @lorenzoPrimi, is it correct to say that the current app does not allow to see logs? If that is correct, can we add a button in the results view of the text, near the place from which one can see the JSON, to allow a user to also see the logs (and perhaps to easily paste them)? I believe this would be very useful.

**Comment by hellais** [comment]
Commenting also here what I said to @bassosimone in private for posterity:

* I believe that in production the issue of identifying versions on mobile apps will not be so much of an issue since we will always know the version of MK given the version number of the app since we are the ones that build and push it (maybe it's useful to include the app specific version number somewhere as well or use the app version number instead of the measurement-kit version number in the logs).

* The specific version in question is the measurement-kit branch feature/ndt-stats since the last commit I made on it

**Comment by lorenzoPrimi** [comment]
At the moment there is no way to see logs for the end user, there was but we removed it because they are not "user friendly"

**Comment by bassosimone** [comment]
I understand that logs are not user friendly, but we *will* have bug reports and since probably they will have to do with the C++ part and I am probably the person that needs to figure out what is going on, I am quite sure that I *will* need to see the logs. Can't we have just another button below of the information for developers (i.e. the expanded JSON) that allows to see them? *Please*?

**Comment by lorenzoPrimi** [comment]
I'll think how to "hide" this button and will let you know.
I don't mean it literally, but put the button in a less visible position

**Comment by bassosimone** [comment]
To be clear, I suggest something like this:

![screen shot 2017-01-25 at 19 45 02](https://cloud.githubusercontent.com/assets/337298/22304342/4b6a886e-e337-11e6-8d9b-04629cb939fa.png)

**Comment by willscott** [comment]
That would need to be exposed in the `ooni-wui` view, right?

**Comment by lorenzoPrimi** [comment]
That is the only place where it can't be. It's a webview.
Maybe I can put it in the top right corner

**Comment by bassosimone** [comment]
Ah, I understand, damn'it. What about: by default you don't see logs but there is a setting that, if you set it on, you have a button allowing you to see the logs (rough but not the default)?

**Comment by lorenzoPrimi** [comment]
Please, we are in the release phase 👎  Let's not change anything, expecially the settings.
We'll only insert a Raw Log button somewhere:
1. Top right corner of the test result
2. Row test result, like where is the view button
3. Sliding left the result row, or right, the opposite of deleting
4. force press a row (don't know how it will work on iOS)
 
I vote for #1 at the moment, any other idea?

**Comment by willscott** [comment]
1 seems reasonable. you could also implement it as a 'copy logs to clipboard' if you don't want to make an extra view/ui.

**Comment by bassosimone** [comment]
I think 1. with an arrow going right (opposite of back) and labelled as "Logs" can fit quite naturally into the current web UI, so :+1: for solution 1

**Comment by lorenzoPrimi** [comment]
Should I make an uitextview with copy and paste feature?

**Comment by bassosimone** [comment]
Yes, I think that would be what we need! (Plus, I'd like to see and learn how you implement disposing of the keyboard when editing done, because I tried that on iOS yesterday and failed!)

**Comment by lorenzoPrimi** [comment]
Added in https://github.com/measurement-kit/ooniprobe-ios/commit/68fb2a5f4b9d3a3d24006d35b24157392514571b

**Comment by bassosimone** [comment]
Excellent, thank you!

**Comment by willscott** [comment]
This continues to occur in the most recent (Feb 02 / v24) release

**Comment by bassosimone** [comment]
@willscott, @lorenzoPrimi:

I think I've figured out what is going on. The culprit in the logs is:

> ip_lookup() failed: error code: 1004

This is "dns error" (sorry not errors have been converted to meaningful names yet).

The other app uses the `system` DNS engine; in OONI mobile we use `libevent. The former calls `getaddrinfo`, the latter takes in input a *single* DNS server IPv{4,6} addr.

But the code in OONI mobile that selects the DNS server IP [explicitly considers only IPv4](https://github.com/measurement-kit/ooniprobe-ios/blob/master/ooniprobe/Model/NetworkMeasurement.mm#L43).

Possible fixes:

1. modify OONI mobile to always use the system DNS (`.set_options("dns/engine", "system")`)

2. modify the DNS selection code mentioned above to also recognise IPv6 (and possibly add more code to make sure that the selected DNS also *does work*)

3. modify our API to allow to pass more than one DNS server to the `libevent` engine and let `libevent` decide which is the best one to use

The easiest fix is 1 (by rolling it out, albeit briefly, we can for example confirm my diagnosis above and know what we're doing that is wrong in @willscott setup).

The disadvantages of solution 1 are:

a. we don't have a thread pool yet (and in any case it wouldn't make sense to flesh it out at this stage of development of v0.4), so each `getaddrinfo` spawns a new short lived thread; do we care?

b. we lose access to low level data that we would otherwise access via `libevent` (it seems however the tests we have don't use such data, plus the real data bonanza will only come when we will enable the `c-ares` engine that literally calls `send()` and `recv()` so we see real *raw* data)

What does not fully convince me of solution 2 is that it may not be enough as a patch (but perhaps if it works for @willscott it works for the whole class of networks with IPv6 only).

I'd rather avoid solution 3, unless we find a very neat way to implement it, because we're quite near a stable release. But perhaps it can be an hot fix where the DNS name server is actually either an atom or a list (we split by comma and iterate over the resulting vector). This may probably be a wise thing to do, given that we may want in the future to use the `libevent` (or `c-ares`) engine for doing DNS related low level tests in scenarios similar to the one that is troubling us.

What do you guys think? What would you guys rather see implemented? Any other idea?

**Comment by hellais** [comment]
I have implemented the above recommended fix (using system DNS) and this will be part of ooniprobe-ios 1.1.0.

@lorenzoPrimi is going to upload this release to the store later tonight and we will be getting a test flight out for it ASAP.

Note: all future test flights will be done from The Tor Project account and not from @lorenzoPrimi personal account so we will have to re-invite you to the test-flight program.

**Comment by willscott** [comment]
Can confirm that tests now run in my environment with 1.1.0 :+1:
